week=[
    [
        [   '-',
            {'lesson':'Основи системного аналізу','type':'(прак.)', 'where':'Meet','link':'https://meet.google.com/mhr-ykwa-yvn'},
            {'lesson':'ООП','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Основи молекулярної біології та біоінформатики','type':'(прак.)', 'where':'Meet','link':'https://meet.google.com/rnk-pgqw-yjo'},
            '-'
        ],
        [   '-',
            {'lesson':'Філософія','type':'(лек.)', 'where':'Zoom','link':'https://us04web.zoom.us/j/9584503319?pwd=U1BrSlZ2dkxuMUVQSDRMMVBOZ0s1UT09'},
            {'lesson':'Доп. предмет','type':'', 'where':'','link':''},
            {'lesson':'Доп. предмет','type':'', 'where':'','link':''},
            '-'
        ],
        [   '-',
            {'lesson':'Основи системного аналізу','type':'(лек.)', 'where':'Meet','link':'https://meet.google.com/mhr-ykwa-yvn'},
            {'lesson':'Обробка та аналіз БМД','type':'(лек.)', 'where':'Zoom','link':'https://us04web.zoom.us/j/78908811232?pwd=_sFuGldgTGrloK17P8eB_xw9SQXIg0.1'},
            {'lesson':'Основи молекулярної біології та біоінформатики','type':'(лек.)', 'where':'Meet','link':'https://meet.google.com/rnk-pgqw-yjo'},
            '-',
        ],
        [   {'lesson':'ООП','type':'(лек.)', 'where':'','link':''},
            '-',
            {'lesson':'Безпека інформаційних систем','type':'(лек.)', 'where':'Zoom','link':'https://us02web.zoom.us/j/5850411662?pwd=VFdVb2hoekovRE56bC8xV1V0RXd3Zz09'},
            '-',
            '-',
        ],
        [   {'lesson':'Обробка та аналіз БМД','type':'(прак.)', 'where':'Zoom','link':'https://us04web.zoom.us/j/78908811232?pwd=_sFuGldgTGrloK17P8eB_xw9SQXIg0.1'},
            {'lesson':'English','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Безпека інформаційних систем','type':'(прак.)', 'where':'Zoom','link':'https://us02web.zoom.us/j/5850411662?pwd=VFdVb2hoekovRE56bC8xV1V0RXd3Zz09'},
            {'lesson':'Філософія','type':'(прак.)', 'where':'','link':''},
            '-',
        ],
        [   {'lesson':'Доп. предмет','type':'', 'where':'','link':''},
            '-',
            '-',
            '-',
            '-',
        ],
        ['Отдыхай, чумба']
    ],
    [
        [   '-',
            {'lesson':'Основи системного аналізу','type':'(прак.)', 'where':'Meet','link':'https://meet.google.com/mhr-ykwa-yvn'},
            {'lesson':'ООП','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Основи молекулярної біології та біоінформатики','type':'(прак.)', 'where':'Meet','link':'https://meet.google.com/rnk-pgqw-yjo'},
            '-',
        ],
        [   '-',
            {'lesson':'Розумні міста','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Психологія','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Доп. предмет','type':'', 'where':'','link':''},
            {'lesson':'Політична наука','type':'(прак.)', 'where':'','link':''},
        ],
        [   '-',
            {'lesson':'Основи системного аналізу','type':'(лек.)', 'where':'Meet','link':'https://meet.google.com/mhr-ykwa-yvn'},
            {'lesson':'Обробка та аналіз БМД','type':'(лек.)', 'where':'Zoom','link':'https://us04web.zoom.us/j/78908811232?pwd=_sFuGldgTGrloK17P8eB_xw9SQXIg0.1'},
            {'lesson':'Основи молекулярної біології та біоінформатики','type':'(лек.)', 'where':'Meet','link':'https://meet.google.com/rnk-pgqw-yjo'},
            '-',
        ],
        [   {'lesson':'ООП','type':'(лек.)', 'where':'','link':''},
            '-',
            {'lesson':'Безпека інформаційних систем','type':'(лек.)', 'where':'Zoom','link':'https://us02web.zoom.us/j/5850411662?pwd=VFdVb2hoekovRE56bC8xV1V0RXd3Zz09'},
            '-',
            '-',
        ],
        [   {'lesson':'Обробка та аналіз БМД','type':'(прак.)', 'where':'Zoom','link':'https://us04web.zoom.us/j/78908811232?pwd=_sFuGldgTGrloK17P8eB_xw9SQXIg0.1'},
            {'lesson':'English','type':'(прак.)', 'where':'','link':''},
            {'lesson':'Безпека інформаційних систем','type':'(прак.)', 'where':'Zoom','link':'https://us02web.zoom.us/j/5850411662?pwd=VFdVb2hoekovRE56bC8xV1V0RXd3Zz09'},
            '-',
            '-',
        ],
        [   {'lesson':'Доп. предмет','type':'', 'where':'','link':''},
            '-',
            '-',
            '-',
            '-',
        ],
        ['Отдыхай, чумба']
    ]
]

paras=[     '<i>1 пара</i>  <b>08:30 - 10:05</b>',
            '<i>2 пара</i>  <b>10:25 - 12:00</b>',
            '<i>3 пара</i>  <b>12:20 - 13:55</b>',
            '<i>4 пара</i>  <b>14:15 - 15:50</b>',
            '<i>5 пара</i>  <b>16:10 - 17:45</b>']

weekdays = {
    0: 'Понедельник',
    1: 'Вторник',
    2: 'Среда',
    3: 'Четверг',
    4: 'Пятница',
    5: 'Суботта',
    6: 'Воскресенье',
    }
